### ISSUE TITLE
1.0 tracking issue

### ISSUE THREAD

**Issue by ChaoticTempest** [near/workspaces-rs#113]
Issue tracking major tasks needed for eventual 1.0 release:
- [ ] Complete and comprehensive docs, such as code docs and tutorials/guides.
- [ ] `near-*` dependencies need to be stabilized, especially `near-account-id` needs to release 1.0, otherwise we risk exposing dependencies that we shouldn't and would cause us to make a 2.0 release sooner rather than later.
- [ ] API consistency between workspaces RS and JS
- [ ] API stabilization mostly for anything that require Worker types. Worker currently takes a generic parameter. That can change in the future. https://github.com/near/workspaces-rs/issues/31 and https://github.com/near/workspaces-rs/issues/37
- [ ] Figure out a clear path for async IO being done inside sandbox and workspaces crate. This could change some of the async API calls we offer, so best to wait for this to better defined before 1.0 is released. https://github.com/near/sandbox/issues/32

optional:
- [ ] near-api-rs, so we can potentially move a lot of the internals in workspaces over, but that's internal and can be changed later.
