### ISSUE TITLE
Workspaces 0.2 tracking issue

### ISSUE THREAD

**Issue by austinabell** [near/workspaces-rs#91]
- [x] fast-forwarding https://github.com/near/workspaces-rs/pull/73
- [x] #88
- [x] #41
---
Optional:
- [ ] #68

**Comment by AustinBaggio** [comment]
Tracking for content: 

- [ ] Update the ReadMe to include motivation (what it is, why you'd use it) & how (install + link to examples)
- [ ] Deprecate sim-tests once content has been updated (See [Dev Rel Jira](https://nearinc.atlassian.net/browse/DR-159))

**Comment by austinabell** [comment]
@ChaoticTempest I see #88 is checked off, but I don't see any changes in workspaces relating to this. Was it explored that there is no better way than just manually installing sandbox?

**Comment by ChaoticTempest** [comment]
@austinabell ahh, I meant to checkoff the sandbox crate versioning part of it needed for 0.2 release, but not the actual version management exposed to the user on workspaces side. So that work hasn't been done yet
